# ========== Hydra 全局配置 ==========
hydra:
  run:
    dir: ${cache_path}/${task}/${model_name}/${dataset_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - estimators: default_estimators
  - stat_calculators: default_calculators
  - _self_

# 定义插值变量
model_name: Llama-3.1-8B
dataset_name: csv_dataset

cache_path: ./workdir/output
save_path: ${hydra.run.dir}

task: qa

# 顶层 dataset 字段，确保 args.dataset 存在
dataset: csv

# 定义 CSV 数据集中的文本和标签列（必须与 CSV 文件中一致）
text_column: statement
label_column: label

# 评估集划分，评估时只需定义 eval_split
eval_split: test

batch_size: 8
load_from_disk: false
ignore_exceptions: false
seed:
  - 1

# ========== 模型配置 ==========
model:
  path: "/workspace/lm-polygraph_test/Llama-3.1-8B"
  load_model_args:
    device_map: "cuda:0"

# ========== CSV 数据集配置 ==========
eval_dataset:
  _target_: lm_polygraph.datasets.CSVDataset
  # 请确保这里的路径是你 CSV 文件的绝对路径
  path: "/workspace/lm-polygraph_test/all_true_false_combined.csv"
  input_key: statement
  reference_key: label

# ========== 不确定性估计 ==========
uncertainty_estimators:
  - name: "mean_pointwise_mutual_information"
  - name: "perplexity"
  - name: "mean_token_entropy"
  - name: "max_token_entropy"

# ========== 生成相关配置 ==========
generation_params:
  generate_until:
    - "\n"

generation:
  do_sample: false
  num_beams: 1
  temperature: 1.0

max_new_tokens: 64

generation_metrics: null
