# ========== Hydra 全局配置 ==========
hydra:
  run:
    dir: ${cache_path}/${task}/${model_name}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - estimators: default_estimators
  - stat_calculators: default_calculators
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'
instruct: false
task: qa
dataset: csv

# 定义模型名称变量，用于路径插值
model_name: Llama-3.1-8B

# CSV 数据集参数（确保字段名称与你 CSV 文件一致）
text_column: statement
label_column: label
eval_split: test

batch_size: 8
load_from_disk: false
ignore_exceptions: false
seed:
  - 1

# ========== 模型配置 ==========
model:
  path: "/workspace/lm-polygraph_test/Llama-3.1-8B"
  load_model_args:
    device_map: "cuda:0"

# ========== CSV 数据集配置 ==========
eval_dataset:
  _target_: lm_polygraph.datasets.CSVDataset
  # 请确认 CSV 文件路径正确且文件可读
  path: "/workspace/lm-polygraph_test/all_true_false_combined.csv"
  input_key: statement
  reference_key: label

# ========== 不确定性估计 ==========
uncertainty_estimators:
  - name: "mean_pointwise_mutual_information"
  - name: "perplexity"
  - name: "mean_token_entropy"
  - name: "max_token_entropy"

# ========== 生成相关配置 ==========
generation_params:
  generate_until:
    - "\n"

generation:
  do_sample: false
  num_beams: 1
  temperature: 1.0

max_new_tokens: 64

generation_metrics: null
